Table users {
  id integer [primary key]
  email varchar [unique, not null]
  password varchar [not null]
  role role [not null]
  created_at timestamptz [not null, default: `now()`]
}

Table products {
  id integer [primary key]
  name varchar [not null]
  description varchar [not null]
  price decimal(10,2) [not null]
  stock integer [not null]
}

Table orders {
  id integer [primary key]
  user_id integer [ref: > users.id, not null]
  status order_status [not null]
  total_price decimal(10,2) [not null]
  created_at timestamptz [not null, default: `now()`]
}

Table order_item {
  id integer [primary key]
  order_id integer [ref: > orders.id, not null]
  product_id integer [ref: > products.id, not null]
  quantity integer [not null]
  price_at_purchase decimal(10,2) [not null]
}

Enum role {
    USER
    ADMIN
}

Enum order_status {
    CREATED
    PAID
    SHIPPED
    CANCELLED
}